spring:
    application:
        name: colegio-cursos-ms
    r2dbc:
        url: r2dbc:mysql://localhost:3390/courses
        username: root-courses
        password: 12345
    kafka:
        producer:
            bootstrap-servers: localhost:9092
        topics:
            welcome: welcome-topic
server:
    port: 8080

