spring:
    application:
        name: colegio-cursos-ms
    r2dbc:
        url: r2dbc:mysql://localhost:3390/courses
        username: root-courses
        password: a1s2d3f4g5h6
    kafka:
        producer:
            bootstrap-servers: localhost:9092
        topics:
            courses-scheduled: courses-scheduled
            enrollments-created: enrollments.created.v1
            students-created: students.created.v1
server:
    port: 8090

